# runtime image
FROM google/cloud-sdk:emulators

ENV PUBSUB_PROJECT=test-project
ENV PUBSUB_TOPIC=test-topic
ENV PUBSUB_SUBSCRIPTION=test-sub
ENV PUBSUB_PORT=8085

COPY cmd/streaminginserts/psemu/pubsub-entrypoint.sh entrypoint.sh
RUN chmod a+x entrypoint.sh
EXPOSE ${PUBSUB_PORT}

ENTRYPOINT ["/entrypoint.sh"]